### ISSUE TITLE
Create Vagrant file for dev environment

### ISSUE THREAD

**Issue by ginja85** [ginja85/footpath#4]

**Comment by sekhat** [comment]
Assign me!

**Comment by sekhat** [comment]
So we are wanting a dev environment with:

* Meteor
* Mongo DB

and that's pretty much it right?

**Comment by ginja85** [comment]
Not sure if relevant but Coffeescript as well

    meteor add coffeescript

**Comment by sekhat** [comment]
Yeah, will get that configured to.

**Comment by sekhat** [comment]
@ginja85 Seems meteor has some issues being under vagrant due to trying to store it's personal mongodb database on a virtualbox shared folder causing issues. There are workarounds for it, but it makes working with vagrant more fiddly.

Since meteor now works on windows however, it might not be required. I suggest we leave this for now, until we show a need to make sure it's all on a linux box of some descript.
